'use client';
import {useEffect,useState} from 'react';
import styles from '../platform-pages.module.css';
type Business={slug:string;name:string;industry:string;description:string;city:string;region:string};
export default function Discover(){
 const [q,setQ]=useState(''),[city,setCity]=useState(''),[industry,setIndustry]=useState(''),[businesses,setBusinesses]=useState<Business[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function search(e?:React.FormEvent){e?.preventDefault();setError('');setLoading(true);try{const p=new URLSearchParams({q,city,industry});const r=await fetch('/api/marketplace?'+p.toString());const d=await r.json();if(!r.ok)throw Error(d.error);setBusinesses(d.businesses||[]);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{search();},[]);
 return <main className={styles.shell}><header className={styles.top}><a className={styles.brand} href="/">SalonFlow</a><nav className={styles.nav}><a href="/pricing">Pricing</a><a href="/signup">List your business</a><a href="/login">Owner login</a></nav></header><section className={styles.hero}><h1>Find your next appointment.</h1><p>Explore service businesses and book directly from their live availability. Listings are reviewed before publication.</p></section><form className={styles.filter} onSubmit={search}><input aria-label="Search services" placeholder="Business or service" value={q} onChange={e=>setQ(e.target.value)}/><input aria-label="City" placeholder="City" value={city} onChange={e=>setCity(e.target.value)}/><select aria-label="Service type" value={industry} onChange={e=>setIndustry(e.target.value)}><option value="">All industries</option>{[['barber','Barbers'],['hair','Hair'],['nails','Nails'],['pet-grooming','Pet grooming'],['custom','Other']].map(([v,n])=><option key={v} value={v}>{n}</option>)}</select><button className={styles.button} type="submit">Search</button></form>{error&&<p role="alert" className={styles.alert}>{error}</p>}{loading?<p>Searching businesses...</p>:<div className={styles.cards}>{businesses.length?businesses.map(b=><article key={b.slug} className={styles.card}><small>{b.industry.replace(/-/g,' ').toUpperCase()}</small><h2>{b.name}</h2><p>{[b.city,b.region].filter(Boolean).join(', ')||'Location available on booking page'}</p><p>{b.description||'View services and current openings.'}</p><a className={styles.button} href={'/book/'+encodeURIComponent(b.slug)+'?source=marketplace'}>View availability</a></article>):<div className={styles.card}><h2>No listings match yet.</h2><p>Try another search or check again as more businesses join the marketplace.</p></div>}</div>}<footer className={styles.footer}>Marketplace bookings are not commission-billed in this development release.</footer></main>;
}
