'use client';
import {useState} from 'react';
export default function PasswordChange(){
 const [oldPassword,setOldPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[confirm,setConfirm]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setMessage('');if(newPassword!==confirm){setMessage('New passwords do not match.');return;}if(newPassword.length<12){setMessage('Use at least 12 characters.');return;}
 setBusy(true);try{const r=await fetch('/api/account/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({currentPassword:oldPassword,newPassword})}),d=await r.json();if(!r.ok)throw Error(d.error);setOldPassword('');setNewPassword('');setConfirm('');setMessage(d.message||'Password updated.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel padded"><h2>Change account password</h2><p className="muted">Use a new unique password of at least 12 characters. Other active sessions will be signed out.</p>{message&&<p role="status" className="notice section-gap">{message}</p>}
 <form onSubmit={submit}><label>Current password<input type="password" required autoComplete="current-password" value={oldPassword} onChange={e=>setOldPassword(e.target.value)}/></label><label>New password<input type="password" required minLength={12} maxLength={128} autoComplete="new-password" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label><label>Confirm new password<input type="password" required minLength={12} maxLength={128} autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><button className="primary" type="submit" disabled={busy}>{busy?'Saving…':'Change password'}</button></form></section>;
}
