'use client';
import {useEffect,useState} from 'react';
import PasswordChange from './owner-password';
type Admin={id:string;email:string;role:string;created_at:string};
export default function PlatformAdminManager(){
 const [admins,setAdmins]=useState<Admin[]>([]),[canManage,setCanManage]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/platform/admins',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setAdmins(d.admins);setCanManage(d.canManageAdmins);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function add(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');setError('');try{const r=await fetch('/api/platform/admins',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})}),d=await r.json();if(!r.ok)throw Error(d.error);setEmail('');setPassword('');await load();setMessage('Administrator created. Share credentials securely.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function revoke(userId:string){if(!window.confirm('Revoke administrator access and sign out active sessions?'))return;setBusy(true);setError('');try{const r=await fetch('/api/platform/admins',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId})}),d=await r.json();if(!r.ok)throw Error(d.error);await load();setMessage('Administrator access revoked.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="admin-manage"><section><h2>Platform administrators</h2><p>Only the primary platform administrator may invite or revoke administrators.</p>{error&&<p role="alert" className="alert">{error}</p>}{message&&<p role="status" className="notice">{message}</p>}{admins.map(a=><div className="admin-person" key={a.id}><span><b>{a.email}</b><small>{a.role==='primary'?'Primary administrator':'Administrator'}</small></span>{canManage&&a.role!=='primary'&&<button className="outline" disabled={busy} onClick={()=>revoke(a.id)}>Revoke access</button>}</div>)}</section>{canManage&&<section><h2>Invite administrator</h2><p>Add a trusted platform administrator with a distinct email and a password of at least 6 characters.</p><form onSubmit={add}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Initial password<input type="password" required minLength={6} maxLength={128} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" disabled={busy} type="submit">Create administrator</button></form></section>}<PasswordChange/></div>;
}
