'use client';
import {useEffect,useState} from 'react';
import styles from '../../platform-pages.module.css';
type Overview={businesses:{count:number;listed:number};subscriptions:{plan_code:string;count:number}[];bookings:number;pendingListings:{id:string;slug:string;name:string;industry:string;city:string;region:string}[];financialStatus:string;estimatedAiCostCents:string};
export default function PlatformAdmin(){
 const [data,setData]=useState<Overview|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState('');
 async function refresh(){try{const r=await fetch('/api/platform/overview',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{refresh();},[]);
 async function moderate(businessId:string,approve:boolean){setBusy(businessId);setError('');try{const r=await fetch('/api/platform/overview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({businessId,approve})});const d=await r.json();if(!r.ok)throw Error(d.error);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 return <main className={styles.shell}><header className={styles.top}><a href="/" className={styles.brand}><img className="selah-logo" src="/brand/logo.svg" alt="SelahFlow" width="380" height="68"/> / Platform Admin</a><nav className={styles.nav}><a href="/discover">Marketplace</a><a href="/business">My business</a></nav></header><section className={styles.hero}><h1>Business platform overview</h1><p>Restricted to platform administrators. Counts represent application records, not financial settlement or profit.</p></section>{error&&<p className={styles.alert} role="alert">{error}</p>}{!data?<p>Loading protected metrics… <a href="/login">Owner login</a></p>:<><div className={styles.gridMetric}><div className={styles.metric}>Businesses<strong>{data.businesses.count}</strong></div><div className={styles.metric}>Listed businesses<strong>{data.businesses.listed}</strong></div><div className={styles.metric}>Appointments<strong>{data.bookings}</strong></div><div className={styles.metric}>Pending listing reviews<strong>{data.pendingListings.length}</strong></div></div><div className={styles.cards}><section className={styles.card}><h2>Subscriptions by tier</h2>{data.subscriptions.map(s=><p key={s.plan_code}>{s.plan_code}: <strong>{s.count}</strong></p>)}<p><small>{data.financialStatus}</small></p></section><section className={styles.card}><h2>AI cost tracking</h2><p>Estimated recorded usage cost: ${(Number(data.estimatedAiCostCents)/100).toFixed(2)}</p><p><small>AI calls are not connected in this version.</small></p></section></div><section className={styles.card}><h2>Marketplace listing approvals</h2>{!data.pendingListings.length?<p>No pending businesses.</p>:data.pendingListings.map(b=><div key={b.id} style={{display:'flex',alignItems:'center',justifyContent:'space-between',flexWrap:'wrap',gap:12,padding:12,borderBottom:'1px solid #40556b'}}><div><strong>{b.name}</strong><p>{b.industry} - {[b.city,b.region].filter(Boolean).join(', ')} - /book/{b.slug}</p></div><div style={{display:'flex',gap:8}}><button className={styles.button} disabled={!!busy} onClick={()=>moderate(b.id,true)}>Approve</button><button className={styles.secondary} disabled={!!busy} onClick={()=>moderate(b.id,false)}>Decline</button></div></div>)}</section></>}<footer className={styles.footer}>No platform subscription billing, processing, or commissions are charged in v1.3.2.</footer></main>;
}
