
export const BUSINESS_INDUSTRIES=[
 ['barber','Barbershop'],['hair','Hair salon / stylist'],['nails','Nail salon / technician'],['lashes','Lash extensions'],['brows','Brow studio'],['makeup','Makeup artist'],['skin-care','Skin care / esthetician'],['spa','Day spa'],['massage','Massage therapy'],['wellness','Wellness / holistic care'],['tattoo','Tattoo studio'],['piercing','Body piercing'],['tanning','Tanning studio'],['waxing','Waxing / hair removal'],
 ['pet-grooming','Pet grooming'],['pet-sitting','Pet sitting / boarding'],['dog-training','Dog training'],['veterinary','Veterinary services'],
 ['fitness','Fitness / personal training'],['yoga','Yoga / Pilates'],['sports-coaching','Sports coaching'],['dance','Dance studio'],['martial-arts','Martial arts'],['swimming','Swim instruction'],
 ['medical','Medical appointments'],['dental','Dental practice'],['mental-health','Mental health / counseling'],['physical-therapy','Physical therapy'],['chiropractic','Chiropractic care'],['nutrition','Nutrition coaching'],
 ['tutoring','Tutoring'],['music-lessons','Music lessons'],['art-lessons','Art lessons'],['language-lessons','Language lessons'],['test-prep','Test preparation'],['career-coaching','Career coaching'],
 ['photography','Photography'],['videography','Videography'],['event-planning','Event planning'],['wedding-services','Wedding services'],['florist','Florist / floral design'],['catering','Catering'],['personal-chef','Personal chef'],
 ['cleaning','Home / office cleaning'],['housekeeping','Housekeeping'],['landscaping','Landscaping / lawn care'],['handyman','Handyman'],['plumbing','Plumbing'],['electrical','Electrical services'],['hvac','HVAC services'],['painting','Painting'],['pest-control','Pest control'],['pool-service','Pool maintenance'],['home-organizing','Home organizing'],['moving','Moving services'],
 ['auto-detailing','Auto detailing'],['auto-repair','Automotive repair'],['car-wash','Car wash'],['mobile-mechanic','Mobile mechanic'],['bike-repair','Bicycle repair'],
 ['accounting','Accounting / bookkeeping'],['tax-preparation','Tax preparation'],['financial-planning','Financial planning'],['legal','Legal consultations'],['notary','Notary services'],['insurance','Insurance consultations'],['real-estate','Real estate consultations'],['property-management','Property management'],
 ['consulting','Business consulting'],['it-support','IT support'],['cybersecurity','Cybersecurity consulting'],['marketing','Marketing services'],['web-design','Website / design services'],['graphic-design','Graphic design'],['virtual-assistant','Virtual assistant'],['translation','Translation / interpreting'],['travel-planning','Travel planning'],
 ['rentals','Equipment / venue rentals'],['subscription-services','Subscription / membership services'],['nonprofit','Nonprofit / community services'],['religious','Religious / pastoral services'],['other','Other / custom business']
] as const;
export const US_STATES=[
 ['AL','Alabama'],['AK','Alaska'],['AZ','Arizona'],['AR','Arkansas'],['CA','California'],['CO','Colorado'],['CT','Connecticut'],['DE','Delaware'],['FL','Florida'],['GA','Georgia'],['HI','Hawaii'],['ID','Idaho'],['IL','Illinois'],['IN','Indiana'],['IA','Iowa'],['KS','Kansas'],['KY','Kentucky'],['LA','Louisiana'],['ME','Maine'],['MD','Maryland'],['MA','Massachusetts'],['MI','Michigan'],['MN','Minnesota'],['MS','Mississippi'],['MO','Missouri'],['MT','Montana'],['NE','Nebraska'],['NV','Nevada'],['NH','New Hampshire'],['NJ','New Jersey'],['NM','New Mexico'],['NY','New York'],['NC','North Carolina'],['ND','North Dakota'],['OH','Ohio'],['OK','Oklahoma'],['OR','Oregon'],['PA','Pennsylvania'],['RI','Rhode Island'],['SC','South Carolina'],['SD','South Dakota'],['TN','Tennessee'],['TX','Texas'],['UT','Utah'],['VT','Vermont'],['VA','Virginia'],['WA','Washington'],['WV','West Virginia'],['WI','Wisconsin'],['WY','Wyoming'],['DC','District of Columbia']
] as const;
export function canonicalState(value:string){const key=(value||'').trim().toLowerCase();const m=US_STATES.find(([code,label])=>code.toLowerCase()===key||label.toLowerCase()===key);return m?.[1]||'';}
