import {db} from './database';
import {requireOwner} from './auth';
import {tokenHash,validOrigin} from '../server/security.mjs';

import {defaultSettings,today} from './defaults';

const reply=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
async function context(req:Request,isPublic=false){const slug=isPublic?new URL(req.url).searchParams.get('slug'):null;const account=isPublic?(slug?await db().prepare("SELECT owner_id AS id FROM businesses WHERE slug=? AND status='active'").bind(slug).first<{id:string}>():await db().prepare('SELECT id FROM users ORDER BY created_at LIMIT 1').first<{id:string}>()):null;const owner=isPublic?account?.id:await requireOwner(req);if(!owner)throw Error('Studio is not configured yet.');const row=await db().prepare('SELECT data FROM settings WHERE owner=?').bind(owner).first<{data:string}>();return {owner,config:row?JSON.parse(row.data):structuredClone(defaultSettings)};}
export async function ownerGet(req:Request){try{const {owner,config}=await context(req);const a=await db().prepare('SELECT * FROM appointments WHERE owner=? ORDER BY date,start').bind(owner).all();const e=await db().prepare('SELECT * FROM events WHERE owner=? ORDER BY created DESC LIMIT 500').bind(owner).all();return reply({config,appointments:a.results.map((r:any)=>({...r,...JSON.parse(r.data)})),events:e.results.map((r:any)=>({...r,...JSON.parse(r.data)}))});}catch(e){return reply({error:(e as Error).message==='AUTH_REQUIRED'?'Please sign in.':'Studio data is temporarily unavailable.'},(e as Error).message==='AUTH_REQUIRED'?401:503);}}
export async function studioPost(req:Request,isPublic=false){try{if(!validOrigin(req))return reply({error:'Invalid origin'},403);const raw=await req.text();if(raw.length>20000)return reply({error:'Request too large.'},413);let b;try{b=JSON.parse(raw);}catch{return reply({error:'Invalid request.'},400);}if(!b||typeof b!=='object')return reply({error:'Invalid request.'},400);if(isPublic&&!['availability','book'].includes(b.action))return reply({error:'Action not permitted.'},403);const {owner,config}=await context(req,isPublic);if(isPublic){if(b.website)return reply({error:'Unable to process request.'},400);const ip=(req.headers.get('x-forwarded-for')||'unknown').split(',').at(-1)!.trim();if(!await takeLimit('public:'+owner+':'+tokenHash(ip),120))return reply({error:'Too many requests. Please try again in 15 minutes.'},429);if(b.action==='book'){if(b.policyAccepted!==true)return reply({error:'Please accept the booking policy.'},400);if(!await takeLimit('book:'+owner+':'+tokenHash(ip),12))return reply({error:'Booking limit reached. Please contact the studio.'},429);if(typeof b.email==='string'&&!await takeLimit('email:'+owner+':'+tokenHash(b.email.trim().toLowerCase()),6))return reply({error:'Too many booking requests for this email. Please contact the studio.'},429);}}const audit=(kind:string,data:any)=>db().prepare('INSERT OR IGNORE INTO events(id,owner,created,kind,data) VALUES(?,?,?,?,?)').bind(typeof b.key==='string'&&/^[0-9a-f-]{36}$/.test(b.key)?b.key:crypto.randomUUID(),owner,new Date().toISOString(),kind,JSON.stringify(data));
if(b.action==='settings'){const c=b.config;if(!c?.name?.trim()||c.name.length>100||!Array.isArray(c.services)||!Array.isArray(c.staff)||!Number.isInteger(c.open)||!Number.isInteger(c.close)||c.open<0||c.close>24||c.open>=c.close||!Number.isInteger(c.buffer)||c.buffer<0||c.buffer>60||c.buffer%15!==0||!Number.isFinite(c.tax)||c.tax<0||c.tax>20)throw Error('Check business name, whole-hour opening times, 15-minute buffer and tax.');for(const s of c.services)if(!s.name||s.price<0||!Number.isFinite(s.price)||!Number.isInteger(s.duration)||s.duration<15||s.duration>480||s.duration%15)throw Error('Service duration must use 15-minute increments; prices cannot be negative.');await db().batch([db().prepare('INSERT INTO settings(owner,data) VALUES(?,?) ON CONFLICT(owner) DO UPDATE SET data=excluded.data').bind(owner,JSON.stringify(c)),audit('settings',{})]);return reply({ok:true});}
if(b.action==='availability'||b.action==='book'){if(!Array.isArray(b.services)||b.services.length>10||!b.services.every((id:unknown)=>typeof id==='string'))throw Error('Choose valid services.');const services=config.services.filter((s:any)=>b.services.includes(s.id));if(!services.length||services.length!==b.services.length)throw Error('Choose valid services.');const staff=config.staff.find((s:any)=>s.id===b.staff);if(!staff||!services.every((s:any)=>staff.services.includes(s.id)))throw Error('Choose a qualified team member.');if(!/^\d{4}-\d{2}-\d{2}$/.test(b.date)||new Date(b.date+'T12:00:00Z').toISOString().slice(0,10)!==b.date||b.date<today()||b.date>new Date(Date.now()+366*86400000).toISOString().slice(0,10))throw Error('Choose a date in the next year.');const duration=services.reduce((a:number,s:any)=>a+s.duration,0);const occupied=await db().prepare('SELECT minute FROM slots WHERE owner=? AND date=? AND staff=?').bind(owner,b.date,b.staff).all<{minute:number}>();const busy=new Set(occupied.results.map(x=>x.minute));const nowParts=new Intl.DateTimeFormat('en-GB',{timeZone:'America/New_York',hour:'2-digit',minute:'2-digit'}).format(new Date()).split(':').map(Number);const available=[];for(let start=config.open*60;start+duration+config.buffer<=config.close*60;start+=15){if(b.date===today()&&start<=nowParts[0]*60+nowParts[1])continue;let free=true;for(let t=start;t<start+duration+config.buffer;t+=15)if(busy.has(t))free=false;if(free)available.push(start);}if(b.action==='availability')return reply({slots:available,duration,price:services.reduce((a:number,s:any)=>a+s.price,0)});
if(b.key){const prior=await db().prepare('SELECT id FROM appointments WHERE owner=? AND id=?').bind(owner,b.key).first();if(prior)return reply({ok:true,id:prior.id});}if(b.expectedPrice!==services.reduce((a:number,s:any)=>a+s.price,0)||b.expectedDuration!==duration)return reply({error:'Service prices or durations changed. Refresh the studio and review your booking again.'},409);if(!available.includes(b.start))return reply({error:'That time is no longer available. Please choose another.'},409);if(typeof b.name!=='string'||typeof b.email!=='string'||!b.name.trim()||b.name.length>100||!/^\S+@\S+\.\S+$/.test(b.email)||b.email.length>200)throw Error('Enter a name and valid email.');const id=typeof b.key==='string'&&/^[0-9a-f-]{36}$/.test(b.key)?b.key:crypto.randomUUID();const data={name:b.name.trim(),email:b.email,phone:String(b.phone||'').slice(0,40),services:services.map((s:any)=>s.name),price:services.reduce((a:number,s:any)=>a+s.price,0),channel:isPublic?'Online booking':b.channel==='Booking portal'?'Booking portal':'Front desk',created:new Date().toISOString()};const statements=[db().prepare('INSERT INTO appointments(id,owner,date,staff,start,duration,data,status) VALUES(?,?,?,?,?,?,?,?)').bind(id,owner,b.date,b.staff,b.start,duration,JSON.stringify(data),'Confirmed')];for(let t=b.start;t<b.start+duration+config.buffer;t+=15)statements.push(db().prepare('INSERT INTO slots(owner,date,staff,minute,appointment) VALUES(?,?,?,?,?)').bind(owner,b.date,b.staff,t,id));statements.push(audit('booking',{appointment:id}));try{await db().batch(statements);}catch(error){if((error as {code?:string}).code!=='23505')throw error;return reply({error:'This slot was just taken. Refresh availability and try again.'},409);}return reply({ok:true,id});}
if(b.action==='status'){if(!['Checked in','Completed','Cancelled','No-show'].includes(b.status))throw Error('Invalid status');const old=await db().prepare('SELECT * FROM appointments WHERE owner=? AND id=?').bind(owner,b.id).first();if(!old) return reply({error:'Appointment not found'},404);if(['Completed','Cancelled','No-show'].includes(String(old.status)))throw Error('This appointment is already closed.');const stm=[db().prepare('UPDATE appointments SET status=? WHERE owner=? AND id=?').bind(b.status,owner,b.id),audit('status',{appointment:b.id,status:b.status})];if(b.status==='Cancelled'||b.status==='No-show')stm.push(db().prepare('DELETE FROM slots WHERE owner=? AND appointment=?').bind(owner,b.id));await db().batch(stm);return reply({ok:true});}
if(b.action==='sale'){if(!Array.isArray(b.items)||!b.items.length)throw Error('Add items to checkout.');const lines=b.items.map((l:any)=>{const item=[...config.services.map((s:any)=>({...s,type:'service',cost:null})),...config.products.map((p:any)=>({...p,type:'product'}))].find((x:any)=>x.id===l.id);if(!item||!Number.isInteger(l.qty)||l.qty<1||l.qty>50)throw Error('Invalid checkout item.');return {...item,qty:l.qty};});const total=lines.reduce((n:number,l:any)=>n+l.qty*l.price,0);await db().batch([audit('cash_sale',{lines,total,tax:total*config.tax/100,payment:'Cash recorded manually'})]);return reply({ok:true});}
if(b.action==='handoff'){if(!String(b.message||'').trim())throw Error('Enter a message');await db().batch([audit('handoff',{message:String(b.message).slice(0,2000),status:'Open'})]);return reply({ok:true});}return reply({error:'Unknown action'},400);
}catch(e){return reply({error:(e as Error).message==='AUTH_REQUIRED'?'Please sign in.':((e as {code?:string}).code?'Unable to save right now. Please try again.':(e as Error).message)||'Unable to save. Please try again.'},(e as Error).message==='AUTH_REQUIRED'?401:400);}}

async function takeLimit(key:string,max:number){const row=await db().prepare("INSERT INTO public_limits(key,count,window_start) VALUES(?,1,now()) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN public_limits.window_start<now()-interval '15 minutes' THEN 1 ELSE public_limits.count+1 END,window_start=CASE WHEN public_limits.window_start<now()-interval '15 minutes' THEN now() ELSE public_limits.window_start END RETURNING count").bind(key).first<{count:number}>();return !!row&&row.count<=max;}
export async function publicGet(req:Request){try{const {config}=await context(req,true);return reply({config:{name:config.name,tagline:config.tagline,address:config.address,phone:config.phone,timezone:config.timezone,open:config.open,close:config.close,buffer:config.buffer,policy:config.policy,services:config.services.map((s:any)=>({id:s.id,name:s.name,category:s.category,duration:s.duration,price:s.price,description:s.description})),staff:config.staff.map((s:any)=>({id:s.id,name:s.name,role:s.role,initials:s.initials,services:s.services}))}});}catch{return reply({error:'Online booking is temporarily unavailable. Please contact the studio.'},503);}}
