'use client';
import {useEffect,useRef,useState} from 'react';
import {Scissors,Clock,MapPin,Check,ChevronLeft,Phone,CalendarDays} from 'lucide-react';
import {today,timeLabel} from '../../lib/defaults';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const bookingApi=()=>{if(typeof window==='undefined')return '/api/booking';const match=window.location.pathname.match(/^\\/book\\/([a-z0-9-]+)\\/?$/);return '/api/booking'+(match?'?slug='+encodeURIComponent(match[1]):'');};
export default function Booking(){
 const [config,setConfig]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[step,setStep]=useState(1),[selected,setSelected]=useState<string[]>([]),[staff,setStaff]=useState(''),[date,setDate]=useState(today()),[times,setTimes]=useState<number[]>([]),[checked,setChecked]=useState(false),[time,setTime]=useState<number|null>(null),[done,setDone]=useState(''),[name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[accepted,setAccepted]=useState(false),[website,setWebsite]=useState('');
 const key=useRef('');const requestNumber=useRef(0);
 async function load(){setError('');try{const r=await fetch(bookingApi());const d=await r.json();if(!r.ok)throw Error(d.error);setConfig(d.config);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();key.current=crypto.randomUUID();},[]);
 const services=config?.services.filter((s:any)=>selected.includes(s.id))||[];
 const price=services.reduce((n:number,s:any)=>n+s.price,0),duration=services.reduce((n:number,s:any)=>n+s.duration,0);
 const eligible=config?.staff.filter((s:any)=>selected.every(id=>s.services.includes(id)))||[];
 async function post(body:any){const r=await fetch(bookingApi(),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to process your request.');return d;}
 function resetTimes(){requestNumber.current++;setTimes([]);setChecked(false);setTime(null);key.current=crypto.randomUUID();}
 async function availability(){const current=++requestNumber.current;setBusy(true);setError('');try{const d=await post({action:'availability',services:selected,staff,date});if(current!==requestNumber.current)return;setTimes(d.slots);setChecked(true);setTime(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function confirmBooking(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const d=await post({action:'book',key:key.current,services:selected,staff,date,start:time,expectedPrice:price,expectedDuration:duration,name,email,phone,policyAccepted:accepted,website});setDone(d.id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!config)return <main className="public-loading"><Scissors size={36}/><h1>Book your next visit.</h1><p role="status">{error||'Loading studio details…'}</p>{error&&<button className="primary" onClick={load}>Try again</button>}</main>;
 return <div className="public-page"><header className="public-header"><a href="/book" className="public-brand"><span className="logo"><Scissors size={24}/></span><div><b>{config.name}</b><small>APPOINTMENT BOOKING</small></div></a><span className="public-header-note">Your time. Your style.</span></header><main className="public-main"><aside className="public-intro"><div className="eyebrow">BOOK YOUR NEXT VISIT</div><h1>Find your next opening.</h1><p>Choose your service, team member, and appointment time.</p><div className="studio-facts"><div><Clock size={18}/><span>{timeLabel(config.open*60)}–{timeLabel(config.close*60)}<small>Daily · Eastern time</small></span></div>{config.address&&!config.address.startsWith('Add your')&&<div><MapPin size={18}/><span>{config.address}</span></div>}{config.phone&&<div><Phone size={18}/><span>{config.phone}</span></div>}</div><div className="public-policy"><h3>Before your visit</h3><p>{config.policy}</p><small>No payment is collected online. Pay at the studio.</small></div><a className="owner-signin" href="/login">Studio owner sign in</a></aside><section className="public-booking panel">
 {done?<div className="booking-success"><span className="success-icon"><Check size={32}/></span><div className="eyebrow">YOU’RE BOOKED</div><h2>See you soon, {name.split(' ')[0]}.</h2><p>{services.map((s:any)=>s.name).join(' + ')}</p><b>{new Date(date+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'})}</b><b>{timeLabel(time!)} Eastern · {config.staff.find((s:any)=>s.id===staff)?.name}</b><p>{money(price)} before applicable tax · Pay at studio</p><small>Confirmation: {done}<br/>Save this screen for your records. Email and text confirmations are not enabled.</small><p className="muted">To change or cancel, contact the studio{config.phone?' at '+config.phone:''}.</p><button className="primary" onClick={()=>window.print()}>Print confirmation</button><a className="outline" href="/book">Book another visit</a></div>:<><div className="steps">{['Service','Time & team','Confirm'].map((label,i)=><div key={label} className={step===i+1?'current':step>i+1?'done':''}><span>{step>i+1?<Check size={14}/>:i+1}</span>{label}</div>)}</div><div className="public-form-body">{error&&<div className="alert" role="alert">{error}</div>}
 {step===1&&<><h2>What brings you in?</h2><p className="muted">Choose one or more services.</p><div className="booking-services">{config.services.map((s:any)=><button key={s.id} className={'booking-service '+(selected.includes(s.id)?'picked':'')} onClick={()=>{setSelected(old=>old.includes(s.id)?old.filter(id=>id!==s.id):[...old,s.id]);setStaff('');resetTimes();}}><span className="select-check">{selected.includes(s.id)&&<Check size={14}/>}</span><div><b>{s.name}</b><small>{s.description}</small><small>{s.duration} minutes</small></div><b>{money(s.price)}</b></button>)}</div></>}
 {step===2&&<><h2>Your chair is waiting.</h2><p className="muted">Find a professional and time that work for you.</p><label>Choose your professional<select value={staff} disabled={busy} onChange={e=>{setStaff(e.target.value);resetTimes();}}><option value="">Select a team member</option>{eligible.map((s:any)=><option key={s.id} value={s.id}>{s.name} · {s.role}</option>)}</select></label>{!eligible.length&&<p className="notice section-gap">No single team member offers this service combination. Go back and choose services from the same specialty.</p>}<label>Choose a date<input type="date" min={today()} value={date} disabled={busy} onChange={e=>{setDate(e.target.value);resetTimes();}}/></label><button className="outline full section-gap" disabled={busy||!staff} onClick={availability}><CalendarDays size={17}/>{busy?'Checking the calendar…':'Show available times'}</button><div className="slot-grid">{times.map(t=><button key={t} className={time===t?'picked':''} onClick={()=>{setTime(t);key.current=crypto.randomUUID();}}>{timeLabel(t)}</button>)}</div>{checked&&!times.length&&<p className="notice">No times are available on this date. Please try another day or team member.</p>}<small>All times are Eastern. Your slot is reserved when you confirm.</small></>}
 {step===3&&<form id="public-confirm" onSubmit={confirmBooking}><h2>Make it official.</h2><p className="muted">Review your visit and add your contact details.</p><div className="booking-summary"><b>{services.map((s:any)=>s.name).join(' + ')}</b><p>{date} · {timeLabel(time!)} Eastern · {duration} minutes</p><p>{config.staff.find((s:any)=>s.id===staff)?.name}</p><b>{money(price)} before applicable tax</b><p>Pay at the studio. No deposit collected online.</p></div><label>Full name<input required name="name" maxLength={100} autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label><label>Email<input required name="email" type="email" maxLength={200} autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Phone (optional)<input name="phone" type="tel" maxLength={40} autoComplete="tel" value={phone} onChange={e=>setPhone(e.target.value)}/></label><div className="honeypot" aria-hidden="true"><label>Leave blank<input tabIndex={-1} autoComplete="off" value={website} onChange={e=>setWebsite(e.target.value)}/></label></div><label className="consent"><input type="checkbox" required checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>I confirm these appointment details and agree to the policy: {config.policy}</span></label><p className="muted">Your details will be shared with the studio to manage your appointment. This does not sign you up for marketing.</p></form>}
 </div><div className="modal-footer"><div><b>{money(price)}</b><small>{duration} minutes</small></div><div className="button-row">{step>1&&<button disabled={busy} className="outline" onClick={()=>{setStep(step-1);setError('');}}><ChevronLeft size={16}/>Back</button>}{step<3?<button className="primary" disabled={busy||!selected.length||(step===2&&time===null)} onClick={()=>{setStep(step+1);setError('');}}>Continue</button>:<button className="primary" form="public-confirm" type="submit" disabled={busy||!accepted}>{busy?'Booking…':'Confirm booking'}</button>}</div></div></>}
 </section></main><footer className="public-footer">{config.name} · Appointment booking</footer></div>;
}
