'use client';
import {useEffect,useRef,useState} from 'react';
import {Shapes,Clock,MapPin,Check,ChevronLeft,Phone,CalendarDays} from 'lucide-react';
import {today,timeLabel} from '../../lib/defaults';
import type {CSSProperties} from 'react';
import {themeStyles} from '../../server/themes.mjs';
import {durationLabel,isTermUnit} from '../../lib/service-terms';
import {googleMapsDirections,displayBusinessAddress} from '../../lib/maps';
import PublicAvailabilityCalendar,{type PublicCalendarDay} from '../components/public-availability-calendar';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const bookingApi=()=>{if(typeof window==='undefined')return '/api/booking';const parts=window.location.pathname.split('/').filter(Boolean);const slug=parts.length===2&&parts[0]==='book'?parts[1]:null;return '/api/booking'+(slug?'?slug='+encodeURIComponent(slug):'');};
export default function Booking(){
 const [config,setConfig]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[step,setStep]=useState(1),[selected,setSelected]=useState<string[]>([]),[staff,setStaff]=useState(''),[date,setDate]=useState(today()),[times,setTimes]=useState<number[]>([]),[sessionAvailability,setSessionAvailability]=useState<Record<number,{remaining:number;capacity:number}>>({}),[calendarView,setCalendarView]=useState<'day'|'week'|'month'>('week'),[calendarAnchor,setCalendarAnchor]=useState(today()),[calendarDays,setCalendarDays]=useState<PublicCalendarDay[]>([]),[calendarBusy,setCalendarBusy]=useState(false),[checked,setChecked]=useState(false),[earliestStart,setEarliestStart]=useState<number|null>(null),[firstAvailable,setFirstAvailable]=useState<number|null>(null),[time,setTime]=useState<number|null>(null),[done,setDone]=useState(''),[pendingApproval,setPendingApproval]=useState(false),[name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[accepted,setAccepted]=useState(false),[website,setWebsite]=useState(''),[customAnswers,setCustomAnswers]=useState<Record<string,string|boolean>>({});
 const key=useRef('');const requestNumber=useRef(0);
 async function load(){setError('');try{const r=await fetch(bookingApi());const d=await r.json();if(!r.ok)throw Error(d.error);setConfig(d.config);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();key.current=crypto.randomUUID();},[]);
 const services=config?.services.filter((s:any)=>selected.includes(s.id))||[];
 const price=services.reduce((n:number,s:any)=>n+s.price,0),duration=services.reduce((n:number,s:any)=>n+s.duration,0);
 const eligible=config?.staff.filter((s:any)=>selected.every(id=>s.services.includes(id)))||[];
 async function post(body:any){const r=await fetch(bookingApi(),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to process your request.');return d;}
 function resetTimes(){requestNumber.current++;setTimes([]);setSessionAvailability({});setEarliestStart(null);setFirstAvailable(null);setChecked(false);setTime(null);key.current=crypto.randomUUID();}
 async function availability(targetDate=date){const current=++requestNumber.current;setBusy(true);setError('');try{const d=await post({action:'availability',services:selected,staff,date:targetDate});if(current!==requestNumber.current)return;setTimes(d.slots);setSessionAvailability(d.sessionAvailability||{});setEarliestStart(typeof d.earliestStart==='number'?d.earliestStart:null);setFirstAvailable(typeof d.firstAvailable==='number'?d.firstAvailable:null);setChecked(true);setTime(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function chooseCalendarDate(nextDate:string){
 setDate(nextDate);
 setCalendarAnchor(nextDate);
 resetTimes();
}
useEffect(()=>{
 if(step!==2||!staff||!selected.length)return;
 void availability(date);
},[step,staff,date,selected.join(',')]);
useEffect(()=>{
 if(step!==2||!staff||!selected.length){setCalendarDays([]);return;}
 let cancelled=false;
 const controller=new AbortController();
 setCalendarBusy(true);
 fetch(bookingApi(),{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,
  body:JSON.stringify({action:'calendar',services:selected,staff,date:calendarAnchor,view:calendarView})})
  .then(async r=>{const data=await r.json();if(!r.ok)throw Error(data.error||'Calendar unavailable.');return data;})
  .then(data=>{if(!cancelled)setCalendarDays(data.days||[]);})
  .catch(error=>{if(!cancelled&&error.name!=='AbortError')setError(error.message);})
  .finally(()=>{if(!cancelled)setCalendarBusy(false);});
 return ()=>{cancelled=true;controller.abort();};
},[calendarAnchor,calendarView,staff,selected.join(','),step]);
async function confirmBooking(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const d=await post({action:'book',key:key.current,services:selected,staff,date,start:time,expectedPrice:price,expectedDuration:duration,name,email,phone,policyAccepted:accepted,website,customAnswers});setDone(d.id);setPendingApproval(d.pending===true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!config)return <main className="public-loading"><Shapes size={36} aria-hidden="true"/><h1>Book your next visit.</h1><p role="status">{error||'Loading studio details…'}</p>{error&&<button className="primary" onClick={load}>Try again</button>}</main>;
 return <div className="public-page" data-selah-theme="true" style={{...themeStyles(config.theme,config.brand_primary,config.brand_background),'--brand-primary':config.brand_primary||'#123F3A','--brand-background':config.brand_background||'#F7F4EC','--purple':config.brand_primary||'#123F3A'} as CSSProperties}><header className="public-header"><a href={config.slug?"/book/"+encodeURIComponent(config.slug):"/book"} className="public-brand"><span className="sf-business-logo-frame">{config.slug?<img className="sf-business-logo-image" src={'/api/branding/logo?slug='+encodeURIComponent(config.slug)} alt={config.name+' logo'} onError={e=>{e.currentTarget.style.display='none';}}/>:<Shapes size={32}/>}</span><div><b>{config.name}</b><small>APPOINTMENT BOOKING</small></div></a><span className="public-header-note">Your time. Your style.</span></header><main className="public-main"><aside className="public-intro"><div className="eyebrow">BOOK YOUR NEXT VISIT</div><h1>Find your next opening.</h1><p>{config.business_model||'Choose your service, team member, and appointment time.'}</p><div className="studio-facts"><div><Clock size={18}/><span>{timeLabel(config.open*60)}–{timeLabel(config.close*60)}<small>Daily · Eastern time</small></span></div>{displayBusinessAddress(config.address)&&<div><MapPin size={18}/><span><a className="sf-directions-link" href={googleMapsDirections(config.address)} target="_blank" rel="noopener noreferrer" aria-label={'Get Google Maps directions to '+config.name}>{config.address} ↗</a></span></div>}{config.phone&&<div><Phone size={18}/><span>{config.phone}</span></div>}</div><div className="public-policy"><h3>Before your visit</h3><p>{config.policy}</p><small>No payment is collected online. Pay at the studio.</small></div><a className="owner-signin" href="/login">Studio owner sign in</a></aside><section className="public-booking panel">
 {done?<div className="booking-success"><span className="success-icon"><Check size={32}/></span><div className="eyebrow">{pendingApproval?'BOOKING REQUEST RECEIVED':'YOU’RE BOOKED'}</div><h2>{pendingApproval?'Awaiting approval, '+name.split(' ')[0]+'.':'See you soon, '+name.split(' ')[0]+'.'}</h2><p>{services.map((s:any)=>s.name).join(' + ')}</p>{pendingApproval&&<p className="sf-approval-wait">Your booking is a request only. Do not assume the appointment is confirmed until the business accepts.</p>}<b>{new Date(date+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'})}</b><b>{timeLabel(time!)} Eastern · {config.staff.find((s:any)=>s.id===staff)?.name}</b><p>{money(price)} before applicable tax · Pay at studio</p><small>{pendingApproval?'Request reference':'Confirmation'}: {done}<br/>{pendingApproval?'Your appointment is NOT confirmed yet. The business owner or designated team member must accept it, and the requested time is not held. Contact the business for an update.':'Save this screen for your records.'} Email, SMS and push notifications are not enabled.</small><p className="muted">{displayBusinessAddress(config.address)&&<a className="sf-directions-link" href={googleMapsDirections(config.address)} target="_blank" rel="noopener noreferrer">Directions to the studio ↗</a>}</p><p className="muted">{pendingApproval?'To check your request or choose a new time, contact the studio':'To change or cancel, contact the studio'}{config.phone?' at '+config.phone:''}.</p><button className="primary" onClick={()=>window.print()}>Print confirmation</button><a className="outline" href={config.slug?"/book/"+encodeURIComponent(config.slug):"/book"}>Book another visit</a></div>:<><div className="steps">{['Service','Time & team','Confirm'].map((label,i)=><div key={label} className={step===i+1?'current':step>i+1?'done':''}><span>{step>i+1?<Check size={14}/>:i+1}</span>{label}</div>)}</div><div className="public-form-body">{error&&<div className="alert" role="alert">{error}</div>}
 {step===1&&<><h2>What brings you in?</h2><p className="muted">Choose one or more services.</p><div className="booking-services">{config.services.map((s:any)=><button key={s.id} disabled={isTermUnit(s.durationUnit||'minutes')} className={'booking-service '+(selected.includes(s.id)?'picked':'')} onClick={()=>{setSelected(old=>old.includes(s.id)?old.filter(id=>id!==s.id):[...old,s.id]);setStaff('');resetTimes();}}><span className="select-check">{selected.includes(s.id)&&<Check size={14}/>}</span><div><b>{s.name}</b><small>{s.description}</small><small>{durationLabel(s)} {isTermUnit(s.durationUnit||'minutes')?'· Contact business to enroll; not an appointment':''}</small></div><b>{money(s.price)}</b></button>)}</div></>}
 {step===2&&<><h2>Your chair is waiting.</h2><p className="muted">Find a professional and time that work for you.</p><label>Choose your professional<select value={staff} disabled={busy} onChange={e=>{setStaff(e.target.value);resetTimes();}}><option value="">Select a team member</option>{eligible.map((s:any)=><option key={s.id} value={s.id}>{s.name} · {s.role}</option>)}</select></label>{!eligible.length&&<p className="notice section-gap">No single team member offers this service combination. Go back and choose services from the same specialty.</p>}<PublicAvailabilityCalendar date={date} anchor={calendarAnchor} mode={calendarView} onMode={setCalendarView} onAnchor={setCalendarAnchor} onSelect={chooseCalendarDate} days={calendarDays} loading={calendarBusy}/><label>Selected date<input type="date" min={today()} value={date} disabled={busy} onChange={e=>chooseCalendarDate(e.target.value)}/></label><button className="outline full section-gap" disabled={busy||!staff} onClick={()=>availability()}><CalendarDays size={17}/>{busy?'Checking the calendar…':checked?'Refresh available times':'Check available times'}</button><div className="slot-grid">{times.map(t=><button key={t} className={time===t?'picked':''} onClick={()=>{setTime(t);key.current=crypto.randomUUID();}}>{timeLabel(t)}{sessionAvailability[t]&&<small> · {sessionAvailability[t].remaining}/{sessionAvailability[t].capacity} slots left</small>}</button>)}</div>{checked&&<div className="sf-booking-earliest-note" role="status"><Clock size={19} aria-hidden="true"/><div><strong>{firstAvailable!==null?'First available: '+timeLabel(firstAvailable)+' Eastern':'No open times for this selection'}</strong>{earliestStart!==null&&<p>{firstAvailable!==null&&firstAvailable>earliestStart?'The next 15-minute booking mark is '+timeLabel(earliestStart)+', but that earlier time is unavailable.':'Bookings may begin at '+timeLabel(earliestStart)+' — the next 15-minute mark.'}</p>}<small>No extra one-hour notice is required. Existing appointments, service duration, cleanup time and opening hours still apply.</small></div></div>}{checked&&!times.length&&<p className="notice">No times are available on this date. Please try another day or team member.</p>}<small>All times are Eastern. If this business requires approval, your seat is reserved only after the request is accepted.</small></>}
 {step===3&&<form id="public-confirm" onSubmit={confirmBooking}><h2>Make it official.</h2><p className="muted">Review your visit and add your contact details.</p><div className="booking-summary"><b>{services.map((s:any)=>s.name).join(' + ')}</b><p>{date} · {timeLabel(time!)} Eastern · {duration} minutes</p><p>{config.staff.find((s:any)=>s.id===staff)?.name}</p><b>{money(price)} before applicable tax</b><p>Pay at the studio. No deposit collected online.</p></div><label>Full name<input required name="name" maxLength={100} autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label><label>Email<input required name="email" type="email" maxLength={200} autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Phone (optional)<input name="phone" type="tel" maxLength={40} autoComplete="tel" value={phone} onChange={e=>setPhone(e.target.value)}/></label>{(config.bookingCustomFields||[]).map((f:any)=><label key={f.id}>{f.label}{f.type==='checkbox'?<input type="checkbox" required={f.required} checked={customAnswers[f.id]===true} onChange={e=>setCustomAnswers(v=>({...v,[f.id]:e.target.checked}))}/>:f.type==='select'?<select required={f.required} value={String(customAnswers[f.id]||'')} onChange={e=>setCustomAnswers(v=>({...v,[f.id]:e.target.value}))}><option value="">Choose an option</option>{(f.options||[]).map((o:string)=><option key={o} value={o}>{o}</option>)}</select>:<input required={f.required} type={['number','date'].includes(f.type)?f.type:'text'} maxLength={f.type==='text'?500:undefined} value={String(customAnswers[f.id]||'')} onChange={e=>setCustomAnswers(v=>({...v,[f.id]:e.target.value}))}/>}</label>)}<div className="honeypot" aria-hidden="true"><label>Leave blank<input tabIndex={-1} autoComplete="off" value={website} onChange={e=>setWebsite(e.target.value)}/></label></div><label className="consent"><input type="checkbox" required checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>I confirm these appointment details and agree to the policy: {config.policy}</span></label><p className="muted">Your details will be shared with the studio to manage your appointment. This does not sign you up for marketing.</p></form>}
 </div><div className="modal-footer"><div><b>{money(price)}</b><small>{duration} minutes</small></div><div className="button-row">{step>1&&<button disabled={busy} className="outline" onClick={()=>{setStep(step-1);setError('');}}><ChevronLeft size={16}/>Back</button>}{step<3?<button className="primary" disabled={busy||!selected.length||(step===2&&time===null)} onClick={()=>{setStep(step+1);setError('');}}>Continue</button>:<button className="primary" form="public-confirm" type="submit" disabled={busy||!accepted}>{busy?'Booking…':'Confirm booking'}</button>}</div></div></>}
 </section></main><footer className="public-footer">{config.name} · Appointment booking<span className="booking-platform-brand"><img src="/brand/symbol.svg" alt="" width="34" height="24"/>Powered by SelahFlow · Your bookings flow. You breathe.</span></footer></div>;
}
