'use client';
import {useState} from 'react';
import styles from '../platform-pages.module.css';
import {BUSINESS_INDUSTRIES,US_STATES} from '../../lib/business-options';

export default function Signup(){
 const [name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[slug,setSlug]=useState(''),[industry,setIndustry]=useState('barber'),[city,setCity]=useState(''),[region,setRegion]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');
  try{const response=await fetch('/api/auth/signup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({businessName:name,email,password,slug,industry,city,region,website:''})});const data=await response.json();if(!response.ok)throw Error(data.error||'Registration failed.');window.location.assign('/registration-status');}
  catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 return <main className={styles.shell}><header className={styles.top}><a className={styles.brand} href="/"><img className="selah-logo" src="/brand/logo.svg" alt="SelahFlow" width="380" height="68"/></a><nav className={styles.nav}><a href="/discover">Find services</a><a href="/pricing">Pricing</a><a href="/login">Owner login</a></nav></header><section className={styles.hero}><h1>Apply to join SelahFlow.</h1><p>Every business must be approved by the primary SelahFlow platform administrator. Once approved, your business will appear automatically in the marketplace and your private dashboard will be activated.</p></section><div className={styles.card} style={{maxWidth:620}}><h2>Create business account</h2>{error&&<p role="alert" className={styles.alert}>{error}</p>}<form onSubmit={submit}><label>Business name<input required maxLength={100} value={name} onChange={e=>{const v=e.target.value;setName(v);if(!slug)setSlug(v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,''));}}/></label><label>Industry<select value={industry} onChange={e=>setIndustry(e.target.value)}>{BUSINESS_INDUSTRIES.map(([v,n])=><option value={v} key={v}>{n}</option>)}</select></label><label>City<input value={city} maxLength={80} autoComplete="address-level2" onChange={e=>setCity(e.target.value)}/></label><label>State<select value={region} onChange={e=>setRegion(e.target.value)}><option value="">Select U.S. state (optional)</option>{US_STATES.map(([code,label])=><option key={code} value={label}>{label}</option>)}</select></label><label>Booking URL name<input required minLength={3} maxLength={60} value={slug} pattern="[a-z0-9][a-z0-9-]{1,58}[a-z0-9]" onChange={e=>setSlug(e.target.value.toLowerCase())}/></label><small>Customers will use /book/{slug||'your-business'}</small><label>Owner email<input type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password (at least 6 characters)<input type="password" autoComplete="new-password" minLength={6} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)}/></label><p><small>Your account starts pending review. Your dashboard and public booking page remain inactive until approved. Your Free plan starts after approval. No card required.</small></p><button disabled={busy} className={styles.button}>{busy?'Creating account…':'Submit application'}</button></form></div><footer className={styles.footer}>SelahFlow v1.3.7 · All new businesses require approval</footer></main>;
}
