'use client';
import {useState} from 'react';
import styles from '../platform-pages.module.css';
const industries=[['barber','Barbershop'],['hair','Hair salon'],['nails','Nails'],['pet-grooming','Pet grooming'],['spa','Spa'],['massage','Massage'],['fitness','Fitness'],['tutoring','Tutoring'],['cleaning','Cleaning'],['auto-detailing','Auto detailing'],['custom','Other business']];
export default function Signup(){
 const [name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[slug,setSlug]=useState(''),[industry,setIndustry]=useState('barber'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');
  try{const response=await fetch('/api/auth/signup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({businessName:name,email,password,slug,industry,website:''})});const data=await response.json();if(!response.ok)throw Error(data.error||'Registration failed.');window.location.assign(data.dashboardUrl||'/studio/'+encodeURIComponent(slug));}
  catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 return <main className={styles.shell}><header className={styles.top}><a className={styles.brand} href="/"><img className="selah-logo" src="/brand/logo.svg" alt="SelahFlow" width="380" height="68"/></a><nav className={styles.nav}><a href="/discover">Find services</a><a href="/pricing">Pricing</a><a href="/login">Owner login</a></nav></header><section className={styles.hero}><h1>Launch your booking page.</h1><p>Join SelahFlow and give customers a simple way to book your business. Your new account starts on the Free plan with no card required.</p></section><div className={styles.card} style={{maxWidth:620}}><h2>Create business account</h2>{error&&<p role="alert" className={styles.alert}>{error}</p>}<form onSubmit={submit}><label>Business name<input required maxLength={100} value={name} onChange={e=>{const v=e.target.value;setName(v);if(!slug)setSlug(v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,''));}}/></label><label>Industry<select value={industry} onChange={e=>setIndustry(e.target.value)}>{industries.map(([v,n])=><option value={v} key={v}>{n}</option>)}</select></label><label>Booking URL name<input required minLength={3} maxLength={60} value={slug} pattern="[a-z0-9][a-z0-9-]{1,58}[a-z0-9]" onChange={e=>setSlug(e.target.value.toLowerCase())}/></label><small>Customers will use /book/{slug||'your-business'}</small><label>Owner email<input type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password (at least 12 characters)<input type="password" autoComplete="new-password" minLength={12} maxLength={256} required value={password} onChange={e=>setPassword(e.target.value)}/></label><p><small>New public accounts have no team or services until you add them in Settings. Marketplace listings require an administrator's approval. Paid subscription checkout and AI calls are not active yet.</small></p><button disabled={busy} className={styles.button}>{busy?'Creating account…':'Create Free account'}</button></form></div><footer className={styles.footer}>SelahFlow v1.3.2 business workspaces</footer></main>;
}
