'use client';
import {useEffect,useState} from 'react';
import styles from '../platform-pages.module.css';
type Profile={id:string;slug:string;name:string;industry:string;description:string;city:string;region:string;is_listed:boolean;listing_requested:boolean;plan_code:string;ai_addon:boolean};
export default function BusinessProfile(){
 const [profile,setProfile]=useState<Profile|null>(null),[name,setName]=useState(''),[description,setDescription]=useState(''),[city,setCity]=useState(''),[region,setRegion]=useState(''),[error,setError]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch('/api/business',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);if(!d.business)throw Error('No business has been created for this account.');setProfile(d.business);setName(d.business.name);setDescription(d.business.description);setCity(d.business.city);setRegion(d.business.region);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();},[]);
 async function save(requestListing:boolean){setBusy(true);setError('');setMsg('');try{const r=await fetch('/api/business',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,description,city,region,requestListing})});const d=await r.json();if(!r.ok)throw Error(d.error);setMsg(requestListing?'Listing requested. Awaiting platform review.':'Business profile saved.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className={styles.shell}><header className={styles.top}><a href="/" className={styles.brand}>SalonFlow / Business Profile</a><nav className={styles.nav}><a href="/">Owner Dashboard</a><a href="/pricing">Plans</a><a href="/discover">Marketplace</a></nav></header><section className={styles.hero}><h1>Business profile</h1><p>Configure how customers see your business and request inclusion in the discovery marketplace.</p></section>{error&&<p className={styles.alert} role="alert">{error}</p>}{msg&&<p className={styles.success} role="status">{msg}</p>}{!profile?<p>Loading profile… <a href="/login">Sign in</a></p>:<section className={styles.card} style={{maxWidth:720}}><p>Your booking link: <a href={'/book/'+profile.slug}>/book/{profile.slug}</a></p><p>Current plan: <strong>{profile.plan_code}</strong> (paid upgrades are not active yet)</p><p>Marketplace status: <strong>{profile.is_listed?'Publicly listed':profile.listing_requested?'Awaiting approval':'Not listed'}</strong></p><label>Business name<input value={name} onChange={e=>setName(e.target.value)} maxLength={100}/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={600} rows={4}/></label><label>City<input value={city} onChange={e=>setCity(e.target.value)} maxLength={80}/></label><label>State or region<input value={region} onChange={e=>setRegion(e.target.value)} maxLength={80}/></label><div style={{display:'flex',flexWrap:'wrap',gap:12,marginTop:22}}><button className={styles.button} disabled={busy} onClick={()=>save(false)}>Save changes</button><button className={styles.secondary} disabled={busy||profile.is_listed||profile.listing_requested} onClick={()=>save(true)}>Request marketplace listing</button></div><p><small>Before requesting a listing, add your service catalog and at least one team member in your owner dashboard Settings. Your business information is not an advertisement until approved.</small></p></section>}</main>;
}
